# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WClnjMTK43X758tibT7t1yAbQpNwcnSu
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn import neighbors

df=pd.read_csv("/content/iris.csv")
df

df['species'] = df['species'].replace({'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2})

df.head(10)

x=df[['sepal_length','sepal_width','petal_length','petal_width']]
y=df['species']

knn = neighbors.KNeighborsClassifier(n_neighbors=6)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

knn.fit(x_train,y_train)

knn.score(x_test,y_test)